[toolchain]
# Rust toolchain for Decrust
# This ensures consistent builds across all environments
channel = "stable"
edition = "2021"
components = ["rustfmt", "clippy"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "x86_64-apple-darwin"]
profile = "default"
